# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 18:01
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_stats_to_table(apps, schema_editor):
    Roster = apps.get_model("my_app", "Roster")
    with open ('stats.csv') as readfile:
        output = csv.DictReader(readfile)
        for row in output:
            Roster.objects.create(id=row["id"], name=row["name"], age=row["age"], position=row["position"], points=row["points"],
                                rebounds=row["rebounds"], assists=row["assists"], steals=row["steals"], blocks=row["blocks"],
                                college=row["college"])

class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_stats_to_table)
    ]
